### ISSUE TITLE
Wikidata status

### ISSUE THREAD

**Issue by salgo60** [salgo60/SvenskaSkolor#2]
**Task:** se till att listor i sv:Wikipedia avspeglas i Wikidata
* [ ] [Lista över läroverk och realskolor i Sverige](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_l%C3%A4roverk_och_realskolor_i_Sverige)
* [ ] [Lista över tekniska läroverk och gymnasier i Sverige](https://sv.m.wikipedia.org/wiki/Lista_%C3%B6ver_tekniska_l%C3%A4roverk_och_gymnasier_i_Sverige)
* [ ] [Lista över folkhögskolor i Sverige](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_folkh%C3%B6gskolor_i_Sverige)
* [ ] [Kategori:Listor_med_anknytning_till_utbildning](https://sv.wikipedia.org/wiki/Kategori:Listor_med_anknytning_till_utbildning)

**Comment by salgo60** [comment]
* [Video](https://www.youtube.com/watch?v=3ZCd1rFm_d4) hur man hämtar json från WIkidata
